import 'dart:ui';
import 'dart:convert';
import 'dart:io' as io;
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart';
import 'package:http/http.dart' as http;
import 'package:image/image.dart' as img;
import 'package:shared_preferences/shared_preferences.dart';

class ModelDetailScreen extends StatefulWidget {
  final String modelId;

  const ModelDetailScreen({super.key, required this.modelId});

  @override
  State<ModelDetailScreen> createState() => _ModelDetailScreenState();
}

class _ModelDetailScreenState extends State<ModelDetailScreen> {
  bool _isMediaSelected = false;
  String? _selectedFileName;
  Uint8List? _selectedFileBytes;
  bool _isAnalyzing = false;
  double _analysisProgress = 0.0;
  String? _resultMessage;

  Map<String, dynamic> _getModelConfig() {
    switch (widget.modelId) {
      case '01':
        return {
          'number': 'MODEL 01',
          'title': 'AI Image Detection',
          'subtitle': 'Detects images generated by DALL-E, Midjourney, and Stable Diffusion.',
          'icon': Icons.image,
          'formats': 'PNG, JPEG, WEBP, AVIF, GIF, TIFF, BMP, RAW · Max 10MB',
        };
      case '02':
        return {
          'number': 'MODEL 02',
          'title': 'Deepfake Face Detection',
          'subtitle': 'Detects face-swapped and manipulated faces using XceptionNet.',
          'icon': Icons.face,
          'formats': 'PNG, JPEG, WEBP, AVIF, GIF, TIFF, BMP, RAW · Max 10MB',
        };
      case '03':
        return {
          'number': 'MODEL 03',
          'title': 'Video Deepfake Analyzer',
          'subtitle': 'Frame-by-frame analysis using OpenCV + per-frame inference.',
          'icon': Icons.movie_outlined,
          'formats': 'MP4, MOV, AVI · Max 50MB',
        };
      case '04':
      default:
        return {
          'number': 'MODEL 04',
          'title': 'AI Content Classification',
          'subtitle': 'Multi-modal ViT classifier for synthetic content.',
          'icon': Icons.auto_awesome,
          'formats': 'PNG, JPEG, WEBP, AVIF, GIF, TIFF, BMP, RAW · Max 10MB',
        };
    }
  }

  void _pickMedia() async {
    try {
      final FileType type;
      final List<String>? allowedExtensions;
      if (widget.modelId == '03') {
        type = FileType.video;
        allowedExtensions = null;
      } else {
        type = FileType.custom;
        allowedExtensions = ['png', 'jpg', 'jpeg', 'webp', 'gif', 'tiff', 'bmp', 'avif', 'raw'];
      }

      final FilePickerResult? result = await FilePicker.pickFiles(
        type: type,
        allowedExtensions: allowedExtensions,
        allowMultiple: false,
        withData: true,
      );

      if (result != null && result.files.single.name.isNotEmpty) {
        Uint8List? bytes = result.files.single.bytes;
        if (bytes == null && !kIsWeb && result.files.single.path != null) {
          bytes = io.File(result.files.single.path!).readAsBytesSync();
        }

        String fileName = result.files.single.name;
        if (widget.modelId != '03' && bytes != null) {
          try {
            final decodedImage = img.decodeImage(bytes);
            if (decodedImage != null) {
              final convertedJpg = img.encodeJpg(decodedImage);
              bytes = Uint8List.fromList(convertedJpg);

              // Change extension to .jpg
              final dotIndex = fileName.lastIndexOf('.');
              final baseName = dotIndex != -1 ? fileName.substring(0, dotIndex) : fileName;
              fileName = '$baseName.jpg';
            }
          } catch (e) {
            debugPrint('Error converting image to JPG: $e');
          }
        }

        setState(() {
          _isMediaSelected = true;
          _selectedFileName = fileName;
          _selectedFileBytes = bytes;
          _resultMessage = null;
        });
        if (!mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Selected $_selectedFileName'),
            behavior: SnackBarBehavior.floating,
            backgroundColor: const Color(0xFF007AFF),
          ),
        );
      }
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error picking file: $e'),
          behavior: SnackBarBehavior.floating,
          backgroundColor: Colors.red,
        ),
      );
    }
  }

  void _startAnalysis() async {
    setState(() {
      _isAnalyzing = true;
      _analysisProgress = 0.0;
    });

    if (widget.modelId == '01') {
      if (_selectedFileBytes == null) {
        setState(() {
          _isAnalyzing = false;
          _resultMessage = 'Error: No file data available.';
        });
        return;
      }

      // Simulate analysis progress animation to 50%
      for (int i = 1; i <= 5; i++) {
        await Future.delayed(const Duration(milliseconds: 150));
        if (!mounted) return;
        setState(() {
          _analysisProgress = i / 10.0;
        });
      }

      try {
        final prefs = await SharedPreferences.getInstance();
        final hfToken = prefs.getString('hf_token') ?? '';
        final headers = <String, String>{
          'Content-Type': 'application/octet-stream',
        };
        if (hfToken.isNotEmpty) {
          headers['Authorization'] = 'Bearer $hfToken';
        }

        final url = Uri.parse('https://api-inference.huggingface.co/models/Ateeqq/ai-vs-human-image-detector');
        final response = await http.post(
          url,
          headers: headers,
          body: _selectedFileBytes,
        );

        if (!mounted) return;

        // Finish progress animation to 100%
        for (int i = 6; i <= 10; i++) {
          setState(() {
            _analysisProgress = i / 10.0;
          });
          await Future.delayed(const Duration(milliseconds: 50));
        }

        if (response.statusCode == 200) {
          final data = json.decode(response.body);
          List<dynamic> predictions = [];
          if (data is List) {
            if (data.isNotEmpty && data[0] is List) {
              predictions = data[0];
            } else {
              predictions = data;
            }
          }

          if (predictions.isNotEmpty) {
            Map<String, dynamic>? bestPrediction;
            double maxScore = -1.0;
            for (var pred in predictions) {
              if (pred is Map && pred.containsKey('score')) {
                final double score = (pred['score'] as num).toDouble();
                if (score > maxScore) {
                  maxScore = score;
                  bestPrediction = Map<String, dynamic>.from(pred);
                }
              }
            }

            if (bestPrediction != null) {
              final String rawLabel = bestPrediction['label'] ?? '';
              final String label = (rawLabel.toLowerCase() == 'ai' || rawLabel.toLowerCase() == 'label_0')
                  ? 'AI Generated'
                  : 'Real / Human-made';
              final double scorePercent = maxScore * 100;
              setState(() {
                _isAnalyzing = false;
                _resultMessage = '$label (${scorePercent.toStringAsFixed(1)}% Confidence)';
              });
            } else {
              setState(() {
                _isAnalyzing = false;
                _resultMessage = 'Error parsing API response.';
              });
            }
          } else {
            setState(() {
              _isAnalyzing = false;
              _resultMessage = 'No predictions returned.';
            });
          }
        } else {
          final errorBody = response.body;
          String errorMsg = 'Inference failed (HTTP ${response.statusCode})';
          try {
            final errData = json.decode(errorBody);
            if (errData is Map && errData.containsKey('error')) {
              errorMsg = errData['error'].toString();
            }
          } catch (_) {}
          setState(() {
            _isAnalyzing = false;
            _resultMessage = errorMsg;
          });
        }
      } catch (e) {
        final prefs = await SharedPreferences.getInstance();
        final hfToken = prefs.getString('hf_token') ?? '';
        String errMsg = 'Error during API call: $e';
        if (hfToken.isEmpty && e.toString().contains('Failed to fetch')) {
          errMsg += '\n\nNote: A Hugging Face API Read Token is required on browsers due to CORS. Click the key icon at the top right to set your token.';
        }
        setState(() {
          _isAnalyzing = false;
          _resultMessage = errMsg;
        });
      }
    } else {
      // Simulate analysis progress animation
      for (int i = 1; i <= 10; i++) {
        await Future.delayed(const Duration(milliseconds: 300));
        if (!mounted) return;
        setState(() {
          _analysisProgress = i / 10.0;
        });
      }

      setState(() {
        _isAnalyzing = false;
        _resultMessage = widget.modelId == '02'
            ? 'Real / Unaltered (98.7% Confidence)'
            : 'Deepfake Detected! (87.5% Confidence)';
      });
    }
  }

  void _showTokenInputDialog(BuildContext context) async {
    final prefs = await SharedPreferences.getInstance();
    final currentToken = prefs.getString('hf_token') ?? '';
    final controller = TextEditingController(text: currentToken);

    if (!context.mounted) return;

    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
          title: const Row(
            children: [
              Text('🤗 ', style: TextStyle(fontSize: 24)),
              Text(
                'Hugging Face Token',
                style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
              ),
            ],
          ),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text(
                'Enter your Hugging Face API Read Token to enable direct inference from the browser (bypasses CORS restrictions).',
                style: TextStyle(fontSize: 12, color: Colors.grey),
              ),
              const SizedBox(height: 16),
              TextField(
                controller: controller,
                obscureText: true,
                decoration: InputDecoration(
                  labelText: 'HF API Token',
                  hintText: 'hf_...',
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
                  prefixIcon: const Icon(Icons.key),
                ),
              ),
            ],
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('Cancel'),
            ),
            ElevatedButton(
              onPressed: () async {
                await prefs.setString('hf_token', controller.text.trim());
                if (!context.mounted) return;
                Navigator.pop(context);
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(
                    content: Text('Hugging Face Token saved successfully!'),
                    behavior: SnackBarBehavior.floating,
                    backgroundColor: Color(0xFF007AFF),
                  ),
                );
              },
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF007AFF),
                foregroundColor: Colors.white,
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
              ),
              child: const Text('Save'),
            ),
          ],
        );
      },
    );
  }

  void _showModelInfoModal(BuildContext context) {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (BuildContext context) {
        return DraggableScrollableSheet(
          initialChildSize: 0.8,
          minChildSize: 0.5,
          maxChildSize: 0.95,
          builder: (_, controller) {
            return Container(
              decoration: const BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.vertical(top: Radius.circular(28)),
              ),
              child: Column(
                children: [
                  Center(
                    child: Container(
                      margin: const EdgeInsets.only(top: 12, bottom: 8),
                      width: 40,
                      height: 5,
                      decoration: BoxDecoration(
                        color: Colors.grey[300],
                        borderRadius: BorderRadius.circular(10),
                      ),
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        const Text(
                          'Model Information',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.bold,
                            color: Color(0xFF333333),
                          ),
                        ),
                        IconButton(
                          icon: const Icon(Icons.close, color: Color(0xFF999999)),
                          onPressed: () => Navigator.pop(context),
                        ),
                      ],
                    ),
                  ),
                  const Divider(height: 1, color: Color(0xFFE5E5E5)),
                  Expanded(
                    child: ListView(
                      controller: controller,
                      padding: const EdgeInsets.all(24),
                      children: [
                        Container(
                          padding: const EdgeInsets.all(16),
                          decoration: BoxDecoration(
                            color: const Color(0xFFFFF9E6),
                            border: Border.all(color: const Color(0xFFFFE0B2)),
                            borderRadius: BorderRadius.circular(16),
                          ),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Row(
                                children: [
                                  const Text(
                                    '🤗',
                                    style: TextStyle(fontSize: 24),
                                  ),
                                  const SizedBox(width: 8),
                                  Container(
                                    padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                                    decoration: BoxDecoration(
                                      color: const Color(0xFFFFB300).withOpacity(0.15),
                                      borderRadius: BorderRadius.circular(6),
                                    ),
                                    child: const Text(
                                      'Hugging Face',
                                      style: TextStyle(
                                        color: Color(0xFFB78103),
                                        fontSize: 11,
                                        fontWeight: FontWeight.bold,
                                      ),
                                    ),
                                  ),
                                  const Spacer(),
                                  const Icon(
                                    Icons.verified,
                                    color: Color(0xFF007AFF),
                                    size: 18,
                                  ),
                                ],
                              ),
                              const SizedBox(height: 12),
                              const Text(
                                'Ateeqq/ai-vs-human-image-detector',
                                style: TextStyle(
                                  fontSize: 15,
                                  fontWeight: FontWeight.bold,
                                  color: Color(0xFF333333),
                                  fontFamily: 'monospace',
                                ),
                              ),
                              const SizedBox(height: 6),
                              const Text(
                                'A fine-tuned model trained on 60,000 AI-generated and 60,000 human images. Based on Siglip architecture.',
                                style: TextStyle(
                                  fontSize: 13,
                                  color: Color(0xFF666666),
                                  height: 1.4,
                                ),
                              ),
                            ],
                          ),
                        ),
                        const SizedBox(height: 24),
                        const Text(
                          'MODEL SPECS',
                          style: TextStyle(
                            fontSize: 11,
                            fontWeight: FontWeight.bold,
                            color: Color(0xFF999999),
                            letterSpacing: 0.5,
                          ),
                        ),
                        const SizedBox(height: 12),
                        GridView.count(
                          shrinkWrap: true,
                          physics: const NeverScrollableScrollPhysics(),
                          crossAxisCount: 2,
                          childAspectRatio: 2.2,
                          crossAxisSpacing: 12,
                          mainAxisSpacing: 12,
                          children: [
                            _buildSpecCard('Model Size', '92.9M params', Icons.settings_input_component),
                            _buildSpecCard('Tensor Type', 'F32', Icons.sd_storage),
                            _buildSpecCard('Architecture', 'Siglip Classifier', Icons.psychology),
                            _buildSpecCard('License', 'Apache-2.0', Icons.description),
                          ],
                        ),
                        const SizedBox(height: 24),
                        const Text(
                          'TRAINING & EVALUATION METRICS',
                          style: TextStyle(
                            fontSize: 11,
                            fontWeight: FontWeight.bold,
                            color: Color(0xFF999999),
                            letterSpacing: 0.5,
                          ),
                        ),
                        const SizedBox(height: 12),
                        Container(
                          decoration: BoxDecoration(
                            border: Border.all(color: const Color(0xFFE0E0E0)),
                            borderRadius: BorderRadius.circular(16),
                          ),
                          child: Column(
                            children: [
                              _buildMetricRow('Final Test Accuracy', '99.23%', isBold: true),
                              const Divider(height: 1, color: Color(0xFFE0E0E0)),
                              _buildMetricRow('Final Test F1 Score', '0.9923', isBold: true),
                              const Divider(height: 1, color: Color(0xFFE0E0E0)),
                              _buildMetricRow('Training Epochs', '5.0'),
                              const Divider(height: 1, color: Color(0xFFE0E0E0)),
                              _buildMetricRow('Total Compute', '51.65 GFLOPs'),
                              const Divider(height: 1, color: Color(0xFFE0E0E0)),
                              _buildMetricRow('Training Loss', '0.0799'),
                              const Divider(height: 1, color: Color(0xFFE0E0E0)),
                              _buildMetricRow('Training Runtime', '2h 39m 49s'),
                              const Divider(height: 1, color: Color(0xFFE0E0E0)),
                              _buildMetricRow('Evaluation Loss', '0.0551'),
                            ],
                          ),
                        ),
                        const SizedBox(height: 24),
                        Container(
                          padding: const EdgeInsets.all(16),
                          decoration: BoxDecoration(
                            color: const Color(0xFFFFF3CD),
                            border: Border.all(color: const Color(0xFFFFEEBA)),
                            borderRadius: BorderRadius.circular(16),
                          ),
                          child: const Row(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Icon(Icons.warning_amber_rounded, color: Color(0xFF856404), size: 20),
                              SizedBox(width: 12),
                              Expanded(
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Text(
                                      'Users Report: Overfitting',
                                      style: TextStyle(
                                        fontSize: 14,
                                        fontWeight: FontWeight.bold,
                                        color: Color(0xFF856404),
                                      ),
                                    ),
                                    SizedBox(height: 4),
                                    Text(
                                      'Some users have reported overfitting issues in real-world scenarios. Predictions may have higher false positive rates for certain lighting conditions or stylized human art.',
                                      style: TextStyle(
                                        fontSize: 12,
                                        color: Color(0xFF856404),
                                        height: 1.4,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                        const SizedBox(height: 24),
                      ],
                    ),
                  ),
                ],
              ),
            );
          },
        );
      },
    );
  }

  Widget _buildSpecCard(String title, String value, IconData icon) {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: const Color(0xFFF8F9FA),
        border: Border.all(color: const Color(0xFFEAEAEA)),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Row(
        children: [
          Icon(icon, color: const Color(0xFF007AFF), size: 20),
          const SizedBox(width: 10),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                  title,
                  style: const TextStyle(
                    fontSize: 10,
                    color: Color(0xFF999999),
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 2),
                Text(
                  value,
                  maxLines: 1,
                  overflow: TextOverflow.ellipsis,
                  style: const TextStyle(
                    fontSize: 13,
                    fontWeight: FontWeight.bold,
                    color: Color(0xFF333333),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildMetricRow(String label, String value, {bool isBold = false}) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(
            label,
            style: TextStyle(
              fontSize: 13,
              color: isBold ? const Color(0xFF333333) : const Color(0xFF666666),
              fontWeight: isBold ? FontWeight.bold : FontWeight.normal,
            ),
          ),
          Text(
            value,
            style: TextStyle(
              fontSize: 13,
              fontWeight: FontWeight.bold,
              color: isBold ? const Color(0xFF007AFF) : const Color(0xFF333333),
            ),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final config = _getModelConfig();
    final IconData modelIcon = config['icon'];

    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        scrolledUnderElevation: 0,
        leadingWidth: 70,
        leading: Center(
          child: Container(
            width: 40,
            height: 40,
            decoration: BoxDecoration(
              color: Colors.white,
              border: Border.all(color: const Color(0xFFE0E0E0)),
              borderRadius: BorderRadius.circular(12),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withOpacity(0.03),
                  blurRadius: 4,
                  offset: const Offset(0, 2),
                ),
              ],
            ),
            child: IconButton(
              icon: const Icon(Icons.chevron_left, color: Color(0xFF333333), size: 20),
              padding: EdgeInsets.zero,
              onPressed: () => Navigator.pop(context),
            ),
          ),
        ),
        title: Text(
          config['number'],
          style: const TextStyle(
            fontSize: 14,
            fontWeight: FontWeight.bold,
            color: Color(0xFF007AFF),
            letterSpacing: 1.0,
          ),
        ),
        centerTitle: false,
        actions: widget.modelId == '01'
            ? [
                Padding(
                  padding: const EdgeInsets.only(right: 8.0),
                  child: Container(
                    width: 40,
                    height: 40,
                    decoration: BoxDecoration(
                      color: Colors.white,
                      border: Border.all(color: const Color(0xFFE0E0E0)),
                      borderRadius: BorderRadius.circular(12),
                      boxShadow: [
                        BoxShadow(
                          color: Colors.black.withOpacity(0.03),
                          blurRadius: 4,
                          offset: const Offset(0, 2),
                        ),
                      ],
                    ),
                    child: IconButton(
                      icon: const Icon(Icons.vpn_key_outlined, color: Color(0xFF007AFF), size: 20),
                      padding: EdgeInsets.zero,
                      onPressed: () => _showTokenInputDialog(context),
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.only(right: 16.0),
                  child: Container(
                    width: 40,
                    height: 40,
                    decoration: BoxDecoration(
                      color: Colors.white,
                      border: Border.all(color: const Color(0xFFE0E0E0)),
                      borderRadius: BorderRadius.circular(12),
                      boxShadow: [
                        BoxShadow(
                          color: Colors.black.withOpacity(0.03),
                          blurRadius: 4,
                          offset: const Offset(0, 2),
                        ),
                      ],
                    ),
                    child: IconButton(
                      icon: const Icon(Icons.info_outline, color: Color(0xFF007AFF), size: 20),
                      padding: EdgeInsets.zero,
                      onPressed: () => _showModelInfoModal(context),
                    ),
                  ),
                ),
              ]
            : null,
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Blue Gradient Model Info Card
              Container(
                padding: const EdgeInsets.all(24.0),
                decoration: BoxDecoration(
                  gradient: const LinearGradient(
                    colors: [Color(0xFF0082FF), Color(0xFF4936DF)],
                    begin: Alignment.topLeft,
                    end: Alignment.bottomRight,
                  ),
                  borderRadius: BorderRadius.circular(24),
                  boxShadow: [
                    BoxShadow(
                      color: const Color(0xFF4936DF).withOpacity(0.2),
                      blurRadius: 15,
                      offset: const Offset(0, 8),
                    ),
                  ],
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Soft Translucent Icon Container
                    Container(
                      width: 52,
                      height: 52,
                      decoration: BoxDecoration(
                        color: Colors.white.withOpacity(0.2),
                        borderRadius: BorderRadius.circular(16),
                      ),
                      child: Icon(
                        modelIcon,
                        color: Colors.white,
                        size: 28,
                      ),
                    ),
                    const SizedBox(height: 16),
                    Text(
                      config['title'],
                      style: const TextStyle(
                        fontSize: 22,
                        fontWeight: FontWeight.bold,
                        color: Colors.white,
                        letterSpacing: -0.5,
                      ),
                    ),
                    const SizedBox(height: 8),
                    Text(
                      config['subtitle'],
                      style: TextStyle(
                        fontSize: 13,
                        color: Colors.white.withOpacity(0.85),
                        height: 1.4,
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 24),

              // Upload Container (Dashed Border)
              Expanded(
                child: CustomPaint(
                  painter: DashedBorderPainter(),
                  child: Container(
                    padding: const EdgeInsets.all(24),
                    child: Center(
                      child: _isAnalyzing
                          ? Column(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                SizedBox(
                                  width: 80,
                                  height: 80,
                                  child: CircularProgressIndicator(
                                    value: _analysisProgress,
                                    strokeWidth: 6,
                                    backgroundColor: const Color(0xFFE8F0FF),
                                    valueColor: const AlwaysStoppedAnimation<Color>(Color(0xFF007AFF)),
                                  ),
                                ),
                                const SizedBox(height: 24),
                                Text(
                                  'Analyzing Media... ${( _analysisProgress * 100).toInt()}%',
                                  style: const TextStyle(
                                    fontSize: 16,
                                    fontWeight: FontWeight.bold,
                                    color: Color(0xFF333333),
                                  ),
                                ),
                                const SizedBox(height: 8),
                                const Text(
                                  'Scanning frame signatures',
                                  style: TextStyle(
                                    fontSize: 13,
                                    color: Color(0xFF999999),
                                  ),
                                ),
                              ],
                            )
                          : _resultMessage != null
                              ? Column(
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  children: [
                                    Container(
                                      width: 64,
                                      height: 64,
                                      decoration: BoxDecoration(
                                        color: _resultMessage!.contains('Real')
                                            ? const Color(0xFFE8F5E9)
                                            : const Color(0xFFFFEBEE),
                                        shape: BoxShape.circle,
                                      ),
                                      child: Icon(
                                        _resultMessage!.contains('Real') ? Icons.check_circle : Icons.warning,
                                        color: _resultMessage!.contains('Real') ? Colors.green : Colors.red,
                                        size: 36,
                                      ),
                                    ),
                                    const SizedBox(height: 20),
                                    Text(
                                      _resultMessage!,
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        fontSize: 18,
                                        fontWeight: FontWeight.bold,
                                        color: _resultMessage!.contains('Real') ? Colors.green : Colors.red,
                                      ),
                                    ),
                                    const SizedBox(height: 12),
                                    ElevatedButton.icon(
                                      onPressed: () {
                                        setState(() {
                                          _isMediaSelected = false;
                                          _selectedFileName = null;
                                          _selectedFileBytes = null;
                                          _resultMessage = null;
                                        });
                                      },
                                      icon: const Icon(Icons.refresh, size: 16),
                                      label: const Text('Reset'),
                                      style: ElevatedButton.styleFrom(
                                        backgroundColor: const Color(0xFFF0F2F5),
                                        foregroundColor: const Color(0xFF333333),
                                        elevation: 0,
                                      ),
                                    ),
                                  ],
                                )
                              : _isMediaSelected
                                  ? Column(
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      children: [
                                        Container(
                                          width: 80,
                                          height: 80,
                                          decoration: BoxDecoration(
                                            color: const Color(0xFFE8F0FF),
                                            borderRadius: BorderRadius.circular(16),
                                          ),
                                          child: Icon(
                                            widget.modelId == '03' ? Icons.play_circle_fill : Icons.insert_drive_file,
                                            color: const Color(0xFF007AFF),
                                            size: 40,
                                          ),
                                        ),
                                        const SizedBox(height: 16),
                                        Text(
                                          _selectedFileName ?? 'Selected File',
                                          textAlign: TextAlign.center,
                                          style: const TextStyle(
                                            fontSize: 15,
                                            fontWeight: FontWeight.bold,
                                            color: Color(0xFF333333),
                                          ),
                                        ),
                                        const SizedBox(height: 8),
                                        const Text(
                                          'File loaded successfully',
                                          style: TextStyle(fontSize: 12, color: Color(0xFF999999)),
                                        ),
                                        const SizedBox(height: 16),
                                        TextButton(
                                          onPressed: _pickMedia,
                                          child: const Text('Change Media'),
                                        ),
                                      ],
                                    )
                                  : Column(
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      children: [
                                        Container(
                                          width: 60,
                                          height: 60,
                                          decoration: BoxDecoration(
                                            color: const Color(0xFFF0F6FF),
                                            borderRadius: BorderRadius.circular(16),
                                          ),
                                          child: const Icon(
                                            Icons.cloud_upload_outlined,
                                            color: Color(0xFF007AFF),
                                            size: 28,
                                          ),
                                        ),
                                        const SizedBox(height: 16),
                                        const Text(
                                          'Upload Media',
                                          style: TextStyle(
                                            fontSize: 16,
                                            fontWeight: FontWeight.bold,
                                            color: Color(0xFF333333),
                                          ),
                                        ),
                                        const SizedBox(height: 6),
                                        Text(
                                          config['formats'],
                                          style: const TextStyle(
                                            fontSize: 12,
                                            color: Color(0xFF999999),
                                          ),
                                        ),
                                        const SizedBox(height: 20),
                                        ElevatedButton(
                                          onPressed: _pickMedia,
                                          style: ElevatedButton.styleFrom(
                                            backgroundColor: const Color(0xFF007AFF),
                                            foregroundColor: Colors.white,
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(30),
                                            ),
                                            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
                                            elevation: 0,
                                          ),
                                          child: const Text(
                                            'Choose from Gallery',
                                            style: TextStyle(
                                              fontSize: 13,
                                              fontWeight: FontWeight.bold,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                    ),
                  ),
                ),
              ),
              const SizedBox(height: 24),

              // Analyze Media Button
              Container(
                height: 54,
                decoration: BoxDecoration(
                  gradient: _isMediaSelected && !_isAnalyzing && _resultMessage == null
                      ? const LinearGradient(
                          colors: [Color(0xFF0082FF), Color(0xFF4936DF)],
                          begin: Alignment.topLeft,
                          end: Alignment.bottomRight,
                        )
                      : LinearGradient(
                          colors: [const Color(0xFFE0E0E0).withOpacity(0.8), const Color(0xFFF0F0F0).withOpacity(0.8)],
                        ),
                  borderRadius: BorderRadius.circular(16),
                  boxShadow: _isMediaSelected && !_isAnalyzing && _resultMessage == null
                      ? [
                          BoxShadow(
                            color: const Color(0xFF4936DF).withOpacity(0.2),
                            blurRadius: 10,
                            offset: const Offset(0, 4),
                          )
                        ]
                      : null,
                ),
                child: ElevatedButton.icon(
                  onPressed: _isMediaSelected && !_isAnalyzing && _resultMessage == null ? _startAnalysis : null,
                  icon: Icon(
                    Icons.search,
                    color: _isMediaSelected && !_isAnalyzing && _resultMessage == null
                        ? Colors.white
                        : const Color(0xFFBBBBBB),
                    size: 20,
                  ),
                  label: Text(
                    'Analyze Media',
                    style: TextStyle(
                      fontSize: 15,
                      fontWeight: FontWeight.bold,
                      color: _isMediaSelected && !_isAnalyzing && _resultMessage == null
                          ? Colors.white
                          : const Color(0xFF999999),
                    ),
                  ),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.transparent,
                    shadowColor: Colors.transparent,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(16),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class DashedBorderPainter extends CustomPainter {
  final Color color;
  final double strokeWidth;
  final double gap;
  final double dashLength;
  final double borderRadius;

  DashedBorderPainter({
    this.color = const Color(0xFFE0E0E0),
    this.strokeWidth = 1.5,
    this.gap = 5.0,
    this.dashLength = 8.0,
    this.borderRadius = 24.0,
  });

  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = color
      ..strokeWidth = strokeWidth
      ..style = PaintingStyle.stroke;

    final RRect rrect = RRect.fromRectAndRadius(
      Rect.fromLTWH(0, 0, size.width, size.height),
      Radius.circular(borderRadius),
    );

    final Path path = Path()..addRRect(rrect);
    final Path dashedPath = Path();

    for (final PathMetric metric in path.computeMetrics()) {
      double distance = 0.0;
      while (distance < metric.length) {
        dashedPath.addPath(
          metric.extractPath(distance, distance + dashLength),
          Offset.zero,
        );
        distance += dashLength + gap;
      }
    }
    canvas.drawPath(dashedPath, paint);
  }

  @override
  bool shouldRepaint(covariant DashedBorderPainter oldDelegate) => false;
}
