import 'dart:ui';
import 'dart:io' as io;
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart';
import 'package:http/http.dart' as http;
import 'package:image/image.dart' as img;
import '../services/api_service.dart';
import '../theme.dart';

class ModelDetailScreen extends StatefulWidget {
  final String modelId;

  const ModelDetailScreen({super.key, required this.modelId});

  @override
  State<ModelDetailScreen> createState() => _ModelDetailScreenState();
}

class _ModelDetailScreenState extends State<ModelDetailScreen>
    with SingleTickerProviderStateMixin {
  bool _isMediaSelected = false;
  String? _selectedFileName;
  Uint8List? _selectedFileBytes;
  bool _isAnalyzing = false;
  bool _cancelled = false;
  _DetectionStage _stage = _DetectionStage.idle;
  String? _resultMessage;
  String? _resultVerdict;
  http.Client? _activeClient;

  Map<String, dynamic> _getModelConfig() {
    switch (widget.modelId) {
      case '01':
        return {
          'number': 'MODEL 01',
          'title': 'AI Image Detection',
          'subtitle': 'Detects images generated by DALL-E, Midjourney, and Stable Diffusion.',
          'icon': Icons.image,
          'formats': 'PNG, JPEG, WEBP, AVIF, GIF, TIFF, BMP, RAW · Max 10MB',
        };
      case '02':
        return {
          'number': 'MODEL 02',
          'title': 'Deepfake Face Detection',
          'subtitle': 'Flags face-swapped and manipulated faces with the Hugging Face deepfake model.',
          'icon': Icons.face,
          'formats': 'PNG, JPEG, WEBP, AVIF, GIF, TIFF, BMP, RAW · Max 10MB',
        };
      case '03':
        return {
          'number': 'MODEL 03',
          'title': 'Video Deepfake Analyzer',
          'subtitle': 'Sample frames are extracted with OpenCV and classified frame by frame.',
          'icon': Icons.movie_outlined,
          'formats': 'MP4, MOV, AVI · Max 50MB',
        };
      case '04':
      default:
        return {
          'number': 'MODEL 04',
          'title': 'AI Content Classification',
          'subtitle': 'Analyzes synthetic content using the shared deepfake detection model.',
          'icon': Icons.auto_awesome,
          'formats': 'PNG, JPEG, WEBP, AVIF, GIF, TIFF, BMP, RAW · Max 10MB',
        };
    }
  }

  static const List<_DetectionStage> _milestones = [
    _DetectionStage.uploading,
    _DetectionStage.processing,
    _DetectionStage.analyzing,
    _DetectionStage.generating,
  ];

  String _stageLabel(_DetectionStage stage) {
    switch (stage) {
      case _DetectionStage.uploading:
        return 'Uploading…';
      case _DetectionStage.processing:
        return 'Processing…';
      case _DetectionStage.analyzing:
        return 'Analyzing…';
      case _DetectionStage.generating:
        return 'Generating Result…';
      case _DetectionStage.completed:
        return 'Completed';
      case _DetectionStage.error:
        return 'Something went wrong';
      case _DetectionStage.idle:
        return 'Ready';
    }
  }

  IconData _stageIcon(_DetectionStage stage) {
    switch (stage) {
      case _DetectionStage.uploading:
        return Icons.cloud_upload_outlined;
      case _DetectionStage.processing:
        return Icons.settings_suggest_outlined;
      case _DetectionStage.analyzing:
        return Icons.psychology_outlined;
      case _DetectionStage.generating:
        return Icons.auto_awesome_outlined;
      default:
        return Icons.check_circle_outline;
    }
  }

  void _showResult(String message) {
    setState(() {
      _isAnalyzing = false;
      _stage = _DetectionStage.completed;
      _resultMessage = message;
      _activeClient?.close();
      _activeClient = null;
    });
  }

  void _showFailure(String message) {
    setState(() {
      _isAnalyzing = false;
      _stage = _DetectionStage.error;
      _resultMessage = message;
      _resultVerdict = null;
      _activeClient?.close();
      _activeClient = null;
    });
  }

  void _cancelAnalysis() {
    _cancelled = true;
    _activeClient?.close();
    _activeClient = null;
    if (mounted) {
      setState(() {
        _isAnalyzing = false;
        _stage = _DetectionStage.idle;
        _resultMessage = null;
        _resultVerdict = null;
      });
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Analysis cancelled. You can try again.'),
          backgroundColor: AppColors.warning,
          behavior: SnackBarBehavior.floating,
        ),
      );
    }
  }

  @override
  void dispose() {
    // Abort any in-flight upload; never leak the http.Client.
    _cancelled = true;
    _activeClient?.close();
    _activeClient = null;
    super.dispose();
  }

  Future<void> _startAnalysis() async {
    if (_isAnalyzing || _selectedFileBytes == null) return;
    _cancelled = false;
    _activeClient = http.Client();
    setState(() {
      _isAnalyzing = true;
      _resultMessage = null;
      _resultVerdict = null;
      _stage = _DetectionStage.uploading;
    });

    // Gentle per-stage pacing so the user always sees progress.
    const step = Duration(milliseconds: 550);
    for (final milestone in _milestones) {
      if (_cancelled || !mounted) {
        _activeClient?.close();
        _activeClient = null;
        return;
      }
      setState(() => _stage = milestone);
      await Future.delayed(step);
    }

    if (_cancelled || !mounted) return;
    setState(() => _stage = _DetectionStage.analyzing);

    try {
      final data = await ApiService.analyzeMediaFile(
        modelId: widget.modelId,
        fileName: _selectedFileName ?? 'media',
        bytes: _selectedFileBytes!,
        client: _activeClient,
      );
      if (_cancelled || !mounted) return;

      // The backend persists the scan; build the user-facing result text.
      final prediction =
          data['prediction'] as Map<String, dynamic>? ?? data['detection'] as Map<String, dynamic>?;
      final label = prediction?['label']?.toString() ?? 'Completed';
      final conf = (prediction?['confidence'] is num)
          ? (prediction!['confidence'] as num).toDouble()
          : 0.0;

      _resultVerdict = prediction?['verdict']?.toString();
      _showResult('$label (${conf.toStringAsFixed(1)}% Confidence)');
    } on ApiException catch (e) {
      if (_cancelled || !mounted) return;
      _showFailure(e.message);
    } catch (e) {
      if (_cancelled || !mounted) return;
      _showFailure('Could not complete the analysis. Please try again.');
    }
  }

  void _pickMedia() async {
    try {
      final FileType type;
      final List<String>? allowedExtensions;
      if (widget.modelId == '03') {
        type = FileType.video;
        allowedExtensions = null;
      } else {
        type = FileType.custom;
        allowedExtensions = ['png', 'jpg', 'jpeg', 'webp', 'gif', 'tiff', 'bmp', 'avif', 'raw'];
      }

      final FilePickerResult? result = await FilePicker.pickFiles(
        type: type,
        allowedExtensions: allowedExtensions,
        allowMultiple: false,
        withData: true,
      );

      if (result != null && result.files.single.name.isNotEmpty) {
        Uint8List? bytes = result.files.single.bytes;
        if (bytes == null && !kIsWeb && result.files.single.path != null) {
          bytes = io.File(result.files.single.path!).readAsBytesSync();
        }

        String fileName = result.files.single.name;
        if (widget.modelId != '03' && bytes != null) {
          try {
            final decodedImage = img.decodeImage(bytes);
            if (decodedImage != null) {
              final convertedJpg = img.encodeJpg(decodedImage);
              bytes = Uint8List.fromList(convertedJpg);

              // Change extension to .jpg
              final dotIndex = fileName.lastIndexOf('.');
              final baseName = dotIndex != -1 ? fileName.substring(0, dotIndex) : fileName;
              fileName = '$baseName.jpg';
            }
          } catch (e) {
            debugPrint('Error converting image to JPG: $e');
          }
        }

        setState(() {
          _isMediaSelected = true;
          _selectedFileName = fileName;
          _selectedFileBytes = bytes;
          _resultMessage = null;
          _resultVerdict = null;
        });
      }
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error picking file: $e'),
          backgroundColor: AppColors.danger,
        ),
      );
    }
  }

  Widget _buildAnalyzingState() {
    final current = _milestones.indexOf(_stage);
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        SizedBox(
          width: 84,
          height: 84,
          child: Stack(
            alignment: Alignment.center,
            children: [
              CircularProgressIndicator(
                strokeWidth: 6,
                backgroundColor: AppColors.surfaceAlt,
                valueColor: const AlwaysStoppedAnimation<Color>(AppColors.primary),
              ),
              Icon(_stageIcon(_stage), color: AppColors.primary, size: 30),
            ],
          ),
        ),
        const SizedBox(height: 24),
        Text(
          _isMediaSelected ? _stageLabel(_stage) : 'Preparing…',
          style: const TextStyle(
            fontSize: 16,
            fontWeight: FontWeight.bold,
            color: AppColors.textPrimary,
          ),
        ),
        const SizedBox(height: 6),
        Text(
          widget.modelId == '03'
              ? 'Analyzing frames — this can take a while for long videos'
              : 'Running the deepfake detection model',
          textAlign: TextAlign.center,
          style: const TextStyle(
            fontSize: 12,
            color: AppColors.textSecondary,
          ),
        ),
        const SizedBox(height: 20),
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            for (var i = 0; i < _milestones.length; i++) ...[
              if (i > 0)
                Container(
                  width: 22,
                  height: 1.5,
                  color: i <= current
                      ? AppColors.primary.withValues(alpha: 0.5)
                      : AppColors.divider,
                ),
              Column(
                children: [
                  CircleAvatar(
                    radius: 14,
                    backgroundColor: i < current
                        ? AppColors.primary
                        : i == current
                            ? AppColors.primary.withValues(alpha: 0.15)
                            : AppColors.surfaceAlt,
                    child: i < current
                        ? const Icon(Icons.check, size: 15, color: Colors.white)
                        : i == current
                            ? const SizedBox(
                                width: 10,
                                height: 10,
                                child: CircularProgressIndicator(
                                  strokeWidth: 2,
                                  color: AppColors.primary,
                                ),
                              )
                            : const Icon(Icons.circle, size: 8, color: AppColors.textHint),
                  ),
                  const SizedBox(height: 6),
                  SizedBox(
                    width: 58,
                    child: Text(
                      _stageLabel(_milestones[i]).replaceAll('…', ''),
                      textAlign: TextAlign.center,
                      style: const TextStyle(
                        fontSize: 9,
                        fontWeight: FontWeight.w600,
                        color: AppColors.textSecondary,
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ],
        ),
        const SizedBox(height: 18),
        TextButton.icon(
          onPressed: _cancelAnalysis,
          icon: const Icon(Icons.close, size: 18, color: AppColors.danger),
          label: const Text(
            'Cancel',
            style: TextStyle(color: AppColors.danger, fontWeight: FontWeight.w600),
          ),
        ),
      ],
    );
  }

  Widget _buildResultState() {
    final String message = _resultMessage ?? 'Scan completed';
    final bool isReal = _resultVerdict == 'Real' ||
        (_resultVerdict == null && message.contains('Real'));
    final Color resultColor = isReal ? AppColors.success : AppColors.danger;
    final Color resultBg = isReal ? AppColors.successBg : AppColors.dangerBg;
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Container(
          width: 84,
          height: 84,
          decoration: BoxDecoration(
            color: resultBg,
            shape: BoxShape.circle,
          ),
          child: Icon(
            isReal ? Icons.check_circle : Icons.gpp_maybe,
            color: resultColor,
            size: 44,
          ),
        ),
        const SizedBox(height: 20),
        Text(
          message,
          textAlign: TextAlign.center,
          style: TextStyle(
            fontSize: 19,
            fontWeight: FontWeight.bold,
            color: resultColor,
            height: 1.3,
          ),
        ),
        const SizedBox(height: 16),
        SizedBox(
          width: 180,
          child: AppSecondaryButton(
            label: 'Scan Another',
            icon: Icons.refresh,
            onPressed: () {
              setState(() {
                _isMediaSelected = false;
                _selectedFileName = null;
                _selectedFileBytes = null;
                _resultMessage = null;
                _resultVerdict = null;
              });
            },
          ),
        ),
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    final config = _getModelConfig();
    final IconData modelIcon = config['icon'];

    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        scrolledUnderElevation: 0,
        leadingWidth: 70,
        leading: Center(
          child: Container(
            width: 40,
            height: 40,
            decoration: BoxDecoration(
              color: Colors.white,
              border: Border.all(color: const Color(0xFFE0E0E0)),
              borderRadius: BorderRadius.circular(12),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withValues(alpha: 0.03),
                  blurRadius: 4,
                  offset: const Offset(0, 2),
                ),
              ],
            ),
            child: IconButton(
              icon: const Icon(Icons.chevron_left, color: Color(0xFF333333), size: 20),
              padding: EdgeInsets.zero,
              onPressed: () => Navigator.pop(context),
            ),
          ),
        ),
        title: Text(
          config['number'],
          style: const TextStyle(
            fontSize: 14,
            fontWeight: FontWeight.bold,
            color: Color(0xFF007AFF),
            letterSpacing: 1.0,
          ),
        ),
        centerTitle: false,
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Blue Gradient Model Info Card
              Container(
                padding: const EdgeInsets.all(24.0),
                decoration: BoxDecoration(
                  gradient: const LinearGradient(
                    colors: [AppColors.gradientStart, AppColors.gradientEnd],
                    begin: Alignment.topLeft,
                    end: Alignment.bottomRight,
                  ),
                  borderRadius: BorderRadius.circular(AppRadius.xl),
                  boxShadow: [
                    BoxShadow(
                      color: AppColors.gradientEnd.withValues(alpha: 0.25),
                      blurRadius: 16,
                      offset: const Offset(0, 8),
                    ),
                  ],
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Soft Translucent Icon Container
                    Container(
                      width: 52,
                      height: 52,
                      decoration: BoxDecoration(
                        color: Colors.white.withValues(alpha: 0.2),
                        borderRadius: BorderRadius.circular(16),
                      ),
                      child: Icon(
                        modelIcon,
                        color: Colors.white,
                        size: 28,
                      ),
                    ),
                    const SizedBox(height: 16),
                    Text(
                      config['title'],
                      style: const TextStyle(
                        fontSize: 22,
                        fontWeight: FontWeight.bold,
                        color: Colors.white,
                        letterSpacing: -0.5,
                      ),
                    ),
                    const SizedBox(height: 8),
                    Text(
                      config['subtitle'],
                      style: TextStyle(
                        fontSize: 13,
                        color: Colors.white.withValues(alpha: 0.85),
                        height: 1.4,
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 24),

              // Upload Container (Dashed Border)
              Expanded(
                child: CustomPaint(
                  painter: DashedBorderPainter(),
                  child: Container(
                    padding: const EdgeInsets.all(24),
                    child: Center(
                      child: _isAnalyzing
                          ? _buildAnalyzingState()
                          : _resultMessage != null
                              ? _buildResultState()
                              : _isMediaSelected
                                  ? Column(
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      children: [
                                        Container(
                                          width: 80,
                                          height: 80,
                                          decoration: BoxDecoration(
                                            color: const Color(0xFFE8F0FF),
                                            borderRadius: BorderRadius.circular(16),
                                          ),
                                          child: Icon(
                                            widget.modelId == '03' ? Icons.play_circle_fill : Icons.insert_drive_file,
                                            color: const Color(0xFF007AFF),
                                            size: 40,
                                          ),
                                        ),
                                        const SizedBox(height: 16),
                                        Text(
                                          _selectedFileName ?? 'Selected File',
                                          textAlign: TextAlign.center,
                                          style: const TextStyle(
                                            fontSize: 15,
                                            fontWeight: FontWeight.bold,
                                            color: Color(0xFF333333),
                                          ),
                                        ),
                                        const SizedBox(height: 8),
                                        const Text(
                                          'File loaded successfully',
                                          style: TextStyle(fontSize: 12, color: Color(0xFF999999)),
                                        ),
                                        const SizedBox(height: 16),
                                        TextButton(
                                          onPressed: _pickMedia,
                                          child: const Text('Change Media'),
                                        ),
                                      ],
                                    )
                                  : Column(
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      children: [
                                        Container(
                                          width: 60,
                                          height: 60,
                                          decoration: BoxDecoration(
                                            color: const Color(0xFFF0F6FF),
                                            borderRadius: BorderRadius.circular(16),
                                          ),
                                          child: const Icon(
                                            Icons.cloud_upload_outlined,
                                            color: Color(0xFF007AFF),
                                            size: 28,
                                          ),
                                        ),
                                        const SizedBox(height: 16),
                                        const Text(
                                          'Upload Media',
                                          style: TextStyle(
                                            fontSize: 16,
                                            fontWeight: FontWeight.bold,
                                            color: Color(0xFF333333),
                                          ),
                                        ),
                                        const SizedBox(height: 6),
                                        Text(
                                          config['formats'],
                                          style: const TextStyle(
                                            fontSize: 12,
                                            color: Color(0xFF999999),
                                          ),
                                        ),
                                        const SizedBox(height: 20),
                                        ElevatedButton.icon(
                                          onPressed: _pickMedia,
                                          style: ElevatedButton.styleFrom(
                                            backgroundColor: AppColors.primary,
                                            foregroundColor: Colors.white,
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(AppRadius.pill),
                                            ),
                                            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 13),
                                            elevation: 0,
                                          ),
                                          icon: const Icon(Icons.photo_library_outlined, size: 18),
                                          label: const Text(
                                            'Choose from Gallery',
                                            style: TextStyle(
                                              fontSize: 13,
                                              fontWeight: FontWeight.bold,
                                            ),
                                          ),
                                        ),
                                      ],
                                    ),
                    ),
                  ),
                ),
              ),
              const SizedBox(height: 24),

              // Analyze Media Button
              AppPrimaryButton(
                label: 'Analyze Media',
                icon: Icons.search,
                enabled: _isMediaSelected &&
                    !_isAnalyzing &&
                    _resultMessage == null,
                loading: _isAnalyzing,
                onPressed: _startAnalysis,
              ),
            ],
          ),
        ),
      ),
    );
  }
}

/// Processing milestones shown while a detection runs.
enum _DetectionStage {
  idle,
  uploading,
  processing,
  analyzing,
  generating,
  completed,
  error,
}

class DashedBorderPainter extends CustomPainter {
  final Color color;
  final double strokeWidth;
  final double gap;
  final double dashLength;
  final double borderRadius;

  DashedBorderPainter({
    this.color = const Color(0xFFE0E0E0),
    this.strokeWidth = 1.5,
    this.gap = 5.0,
    this.dashLength = 8.0,
    this.borderRadius = 24.0,
  });

  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = color
      ..strokeWidth = strokeWidth
      ..style = PaintingStyle.stroke;

    final RRect rrect = RRect.fromRectAndRadius(
      Rect.fromLTWH(0, 0, size.width, size.height),
      Radius.circular(borderRadius),
    );

    final Path path = Path()..addRRect(rrect);
    final Path dashedPath = Path();

    for (final PathMetric metric in path.computeMetrics()) {
      double distance = 0.0;
      while (distance < metric.length) {
        dashedPath.addPath(
          metric.extractPath(distance, distance + dashLength),
          Offset.zero,
        );
        distance += dashLength + gap;
      }
    }
    canvas.drawPath(dashedPath, paint);
  }

  @override
  bool shouldRepaint(covariant DashedBorderPainter oldDelegate) => false;
}
